### ISSUE TITLE
Really Nice but License?

### ISSUE THREAD

**Issue by mgiaco** [open-LIN/open-LIN-c#1]
Hello,

What License are you using? 
Many thanks.
cheers mathias

**Comment by Lukasz-Juranek** [comment]
I've updated licensing info and readme see
https://github.com/open-LIN/open-LIN-c/blob/master/LICENSE

Regards,

pon., 5 sie 2019 o 12:12 Mathias Giacomuzzi <notifications@github.com>
napisał(a):

**Comment by mgiaco** [comment]
Many thanks
